version: "3.8"

services:
  bot:
    container_name: "shop-card-bot"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TOKEN: telegram_bot_token
      DATABASE_URL: postgresql://bot:bot@database:5432/bot
    volumes:
      - .:/bot
    command: sh -c "alembic upgrade head && python bot.py"
    restart: always
    depends_on:
      - db


  db:
    container_name: "shop-card-database"
    hostname: database
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: bot
      POSTGRES_PASSWORD: bot
      POSTGRES_DB: bot
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always
