"""empty message

Revision ID: a0fd89e56361
Revises: 
Create Date: 2023-11-15 10:35:33.527693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0fd89e56361'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barcode_types',
    sa.Column('name', sa.VARCHAR(length=12), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column("is_admin", sa.BOOLEAN(), nullable=False, default=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shops',
    sa.Column('name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('barcode_type', sa.VARCHAR(length=12), server_default='Code128', nullable=False),
    sa.ForeignKeyConstraint(['barcode_type'], ['barcode_types.name'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user_cards',
    sa.Column('id', sa.INT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('shop', sa.VARCHAR(length=128), nullable=False),
    sa.Column('barcode', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['shop'], ['shops.name'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cards')
    op.drop_table('shops')
    op.drop_table('users')
    op.drop_table('barcode_types')
    # ### end Alembic commands ###
